# Java Sample
FROM adoptopenjdk/openjdk15

# Python 3.9 (For local emulator)
RUN apt-get update && apt-get install -y python3.9 python3-pip && \
    ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip && \
    apt-get autoremove && apt-get clean

COPY . /code
