#!/usr/bin/env bash

cd /code

DEPOT=$1
TIME_MATRIX_JSON_PATH=$2
LOADS_JSON_PATH=$3
ROUTE_OUT_PATH=$4
TIME_LIMIT_SEC=$5
PROCESSED_PATH=/dest/time_matrix_$DEPOT.json

# Sample command
#echo $DEPOT $PROCESSED_PATH $LOADS_JSON_PATH $ROUTE_OUT_PATH
/dest/solution $DEPOT $PROCESSED_PATH $LOADS_JSON_PATH $ROUTE_OUT_PATH

#python3 GA.py $DEPOT $PROCESSED_PATH $LOADS_JSON_PATH $ROUTE_OUT_PATH $TIME_MATRIX_JSON_PATH